"""initial

Revision ID: 7ecbee53ff48
Revises: 
Create Date: 2026-02-14 06:28:13.306951
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '7ecbee53ff48'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', postgresql.ENUM('ADMIN', 'BUYER', 'SELLER', name='user_role'), nullable=False),
    sa.Column('shop_name', sa.String(length=200), nullable=True),
    sa.Column('is_individual', sa.Boolean(), nullable=False),
    sa.Column('address_street', sa.Text(), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_long', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('phone_listings',
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('AVAILABLE', 'SOLD', 'PENDING', name='listing_status'), nullable=False),
    sa.Column('phone_type', postgresql.ENUM('NEW', 'USED', name='phone_type'), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ram_gb', sa.Integer(), nullable=False),
    sa.Column('storage_gb', sa.Integer(), nullable=False),
    sa.Column('battery_capacity_mah', sa.Integer(), nullable=False),
    sa.Column('camera_resolution_mp', sa.Integer(), nullable=False),
    sa.Column('thumbnail_image', sa.Text(), nullable=True),
    sa.Column('additional_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('battery_health_percent', sa.SmallInteger(), nullable=True),
    sa.Column('pta_approved', sa.Boolean(), nullable=True),
    sa.Column('condition_rating', sa.SmallInteger(), nullable=True, comment='1-10 scale'),
    sa.Column('defects_description', sa.Text(), nullable=True),
    sa.Column('accessories_included', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processor_name', sa.String(length=100), nullable=True),
    sa.Column('warranty_period', sa.String(length=50), nullable=True, comment='e.g. 12 months'),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_long', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_listings_brand'), 'phone_listings', ['brand'], unique=False)
    op.create_index(op.f('ix_phone_listings_seller_id'), 'phone_listings', ['seller_id'], unique=False)
    op.create_table('orders',
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('CREATED', 'ADMIN_REVIEW', 'MEETING_SCHEDULED', 'COMPLETED', 'CANCELLED', name='order_status'), nullable=False),
    sa.Column('agreed_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('meeting_location', sa.Text(), nullable=True),
    sa.Column('meeting_notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['phone_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_buyer_id'), 'orders', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_orders_listing_id'), 'orders', ['listing_id'], unique=False)
    op.create_index(op.f('ix_orders_seller_id'), 'orders', ['seller_id'], unique=False)
    op.create_table('messages',
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('message_type', postgresql.ENUM('TEXT', 'IMAGE', 'SYSTEM', name='message_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_order_id'), 'messages', ['order_id'], unique=False)
    op.create_index(op.f('ix_messages_receiver_id'), 'messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_receiver_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_order_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_orders_seller_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_listing_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_phone_listings_seller_id'), table_name='phone_listings')
    op.drop_index(op.f('ix_phone_listings_brand'), table_name='phone_listings')
    op.drop_table('phone_listings')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
