"""add_chat_recipient_type

Revision ID: f38ec14738e4
Revises: 663534e2040c
Create Date: 2026-02-14 16:37:36.137351
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
"""add_chat_recipient_type

Revision ID: f38ec14738e4
Revises: 663534e2040c
Create Date: 2026-02-14 16:37:36.137351
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = 'f38ec14738e4'
down_revision: Union[str, None] = '663534e2040c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    recipient_type = postgresql.ENUM('GROUP', 'BUYER_ONLY', 'SELLER_ONLY', 'ADMIN_ONLY', name='recipient_type')
    recipient_type.create(op.get_bind())
    op.add_column('messages', sa.Column('recipient_type', recipient_type, nullable=False))
    op.add_column('messages', sa.Column('is_system_message', sa.Boolean(), nullable=False))
    op.alter_column('messages', 'receiver_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'receiver_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('messages', 'is_system_message')
    op.drop_column('messages', 'recipient_type')
    postgresql.ENUM('GROUP', 'BUYER_ONLY', 'SELLER_ONLY', 'ADMIN_ONLY', name='recipient_type').drop(op.get_bind())
    # ### end Alembic commands ###
