/**
 * Comprehensive list of Pakistani cities grouped by province/region.
 * Used for city selection during registration and profile editing.
 */

export const PAKISTANI_CITIES: { province: string; cities: string[] }[] = [
    {
        province: "Punjab",
        cities: [
            "Lahore",
            "Rawalpindi",
            "Faisalabad",
            "Multan",
            "Gujranwala",
            "Sialkot",
            "Sargodha",
            "Bahawalpur",
            "Sheikhupura",
            "Jhang",
            "Rahim Yar Khan",
            "Sahiwal",
            "Gujrat",
            "Wah Cantonment",
            "Jhelum",
            "Kasur",
            "Mianwali",
            "Chiniot",
            "Okara",
            "Dera Ghazi Khan",
            "Hafizabad",
            "Muzaffargarh",
            "Attock",
            "Vehari",
            "Khanewal",
            "Chakwal",
            "Mandi Bahauddin",
            "Toba Tek Singh",
            "Kamoke",
            "Layyah",
            "Bhakkar",
            "Pakpattan",
            "Lodhran",
            "Narowal",
            "Rajanpur",
        ],
    },
    {
        province: "Sindh",
        cities: [
            "Karachi",
            "Hyderabad",
            "Sukkur",
            "Larkana",
            "Nawabshah",
            "Mirpur Khas",
            "Jacobabad",
            "Shikarpur",
            "Khairpur",
            "Thatta",
            "Dadu",
            "Badin",
            "Tando Allahyar",
            "Tando Adam",
            "Umerkot",
            "Sanghar",
            "Ghotki",
            "Kashmore",
        ],
    },
    {
        province: "Khyber Pakhtunkhwa",
        cities: [
            "Peshawar",
            "Mardan",
            "Abbottabad",
            "Mingora",
            "Mansehra",
            "Swabi",
            "Kohat",
            "Dera Ismail Khan",
            "Charsadda",
            "Nowshera",
            "Bannu",
            "Haripur",
            "Chitral",
            "Batkhela",
            "Karak",
            "Lakki Marwat",
            "Tank",
            "Hangu",
        ],
    },
    {
        province: "Balochistan",
        cities: [
            "Quetta",
            "Gwadar",
            "Turbat",
            "Zhob",
            "Hub",
            "Chaman",
            "Sibi",
            "Khuzdar",
            "Loralai",
            "Pishin",
            "Dera Murad Jamali",
            "Nushki",
            "Kalat",
            "Mastung",
        ],
    },
    {
        province: "Islamabad Capital Territory",
        cities: ["Islamabad"],
    },
    {
        province: "Azad Jammu & Kashmir",
        cities: [
            "Muzaffarabad",
            "Mirpur",
            "Rawalakot",
            "Bagh",
            "Kotli",
            "Bhimber",
            "Pallandri",
        ],
    },
    {
        province: "Gilgit-Baltistan",
        cities: ["Gilgit", "Skardu", "Hunza", "Chilas", "Ghizer"],
    },
];

/** Flat array of all city names, sorted alphabetically */
export const ALL_CITIES: string[] = PAKISTANI_CITIES.flatMap((p) => p.cities).sort();
